name: PRA
channels:
  - conda-forge
  - defaults
dependencies:
  - graph-tool
  - pip
  - python=3.7
  - pyqtgraph
  - pip:
    - backcall==0.2.0
    - cached-property==1.5.2
    - cycler==0.10.0
    - cython==0.29.21
    - dcimg==0.6.0.post1
    - decorator==4.4.2
    - et-xmlfile==1.0.1
    - futures==3.1.1
    - h5py==3.1.0
    - imageio==2.9.0
    - ipython==7.24.1
    - ipython-genutils==0.2.0
    - jdcal==1.4.1
    - jedi==0.18.0
    - joblib==1.0.0
    - kiwisolver==1.3.1
    - llvmlite==0.35.0
    - matplotlib==3.3.3
    - matplotlib-inline==0.1.2
    - natsort==7.1.1
    - networkx==2.5
    - numba==0.52.0
    - opencv-python==4.5.1.48
    - openpyxl==3.0.6
    - pandas==1.2.1
    - parso==0.8.2
    - pathlib2==2.3.5
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.1.0
    - prompt-toolkit==3.0.18
    - protobuf==3.14.0
    - ptyprocess==0.7.0
    - pygments==2.9.0
    - pyhamcrest==2.0.2
    - pyparsing==2.4.7
    - pystripe==0.2.0
    - python-dateutil==2.8.1
    - pytz==2020.5
    - pywavelets==1.1.1
    - scikit-image==0.18.1
    - scikit-learn==0.24.1
    - scipy==1.6.0
    - seaborn==0.11.1
    - simpleitk==2.0.2
    - tensorboardx==2.1
    - threadpoolctl==2.1.0
    - tifffile==2021.1.11
    - torch==1.7.1
    - torchvision==0.8.2
    - tqdm==4.56.0
    - traitlets==5.0.5
    - typing-extensions==3.7.4.3
    - wcwidth==0.2.5
    - xlrd==2.0.1
    - xvfbwrapper==0.2.9

